apiVersion: v1
kind: Service
metadata:
  name: oncall
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090" 
    prometheus.io/path: "/metrics/mysql"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: oncall
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics  
      port: 9090
      targetPort: 9090