apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-prober
  labels:
    app: oncall-prober
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oncall-prober
  template:
    metadata:
      labels:
        app: oncall-prober
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9081"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: prober
          image: gabmaryam/oncall-prober:0.4
          env:
            - name: ONCALL_EXPORTER_API_URL
              value: "http://oncall:8080"  # ← ваш сервис
            - name: ONCALL_EXPORTER_SCRAPE_INTERVAL
              value: "30"
            - name: ONCALL_EXPORTER_LOG_LEVEL
              value: "INFO"
            - name: ONCALL_EXPORTER_METRICS_PORT
              value: "9081"
          ports:
            - containerPort: 9081
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9081
            initialDelaySeconds: 10
            periodSeconds: 30